// Copies the big binary assets out of node_modules into /public so they are
// served as plain static files (and cached by the browser after the first use).
import { cpSync, mkdirSync, existsSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const nm = (p) => resolve(root, 'node_modules', p);
const pub = (p) => resolve(root, 'public', p);

function copy(from, to) {
  if (!existsSync(from)) {
    console.error(`[copy-assets] missing: ${from} (did you run npm install?)`);
    process.exit(1);
  }
  mkdirSync(dirname(to), { recursive: true });
  cpSync(from, to, { recursive: true });
}

// Ghostscript (PDF compression engine, ~16 MB, loaded only when a PDF is compressed).
// public/engine/gs-worker.js (committed) drives these two files.
copy(nm('@jspawn/ghostscript-wasm/gs.js'), pub('engine/gs.js'));
copy(nm('@jspawn/ghostscript-wasm/gs.wasm'), pub('engine/gs.wasm'));
copy(nm('@jspawn/ghostscript-wasm/LICENSE'), pub('engine/LICENSE-ghostscript.txt'));

// qpdf (locks, unlocks, merges and splits PDFs without re-drawing them). ~1.3 MB.
copy(nm('@neslinesli93/qpdf-wasm/dist/qpdf.js'), pub('engine/qpdf.js'));
copy(nm('@neslinesli93/qpdf-wasm/dist/qpdf.wasm'), pub('engine/qpdf.wasm'));

// Google Fonts for the PDF editor's "More fonts" list. Plain .woff (not .woff2): the WebAssembly
// font subsetter used when saving a PDF (fontkit) can only read the older, simpler .woff format.
const GFONTS = [
  ['inter', 'inter', ['400', '700', '400-italic', '700-italic']],
  ['roboto', 'roboto', ['400', '700', '400-italic', '700-italic']],
  ['poppins', 'poppins', ['400', '700', '400-italic', '700-italic']],
  ['playfair-display', 'playfair', ['400', '700', '400-italic', '700-italic']],
  ['merriweather', 'merriweather', ['400', '700', '400-italic', '700-italic']],
  ['caveat', 'caveat', ['400', '700']],
];
const CSS_NAMES = {
  inter: 'Fitsize Inter',
  roboto: 'Fitsize Roboto',
  poppins: 'Fitsize Poppins',
  playfair: 'Fitsize Playfair',
  merriweather: 'Fitsize Merriweather',
  caveat: 'Fitsize Caveat',
};
let fontsCss = '/* Generated by scripts/copy-assets.mjs. Used only by the PDF editor\'s "More fonts" list. */\n';
for (const [pkg, short, weights] of GFONTS) {
  for (const w of weights) {
    const style = w.endsWith('italic') ? 'italic' : 'normal';
    const weight = w.split('-')[0];
    const src = `@fontsource/${pkg}/files/${pkg}-latin-${weight}-${style}.woff`;
    const file = `${short}-${weight}${style === 'italic' ? 'i' : ''}.woff`;
    copy(nm(src), pub(`fonts/${file}`));
    fontsCss += `@font-face { font-family: '${CSS_NAMES[short]}'; font-weight: ${weight}; font-style: ${style}; font-display: swap; src: url('/fonts/${file}') format('woff'); }\n`;
  }
}
writeFileSync(pub('fonts/fonts.css'), fontsCss);

// pdf.js helper data (fonts, colour profiles, JPEG2000/JBIG2 decoders)
for (const dir of ['cmaps', 'standard_fonts', 'wasm', 'iccs']) {
  copy(nm(`pdfjs-dist/${dir}`), pub(`pdfjs/${dir}`));
}
console.log('[copy-assets] done');
